#!/usr/bin/perl

#-- Creates a new fasta file containing a database, reading the clusters generated by mmseqs2
#-- The resultiung fasta file is ready to create a new LCA db using make_databases_newdb.pl

use Tie::IxHash;
use strict;

my %accumtax;
tie %accumtax,"Tie::IxHash";

my %taxstore;
my $dbname=$ARGV[0] || "nr.gz";
print "Reading database in $dbname\n";
if($dbname=~/gz$/) { open(in1,"zcat $dbname |") || die "Cannot open input file in $dbname\n"; }
else { open(in1,$dbname) || die "Cannot open input file in $dbname\n"; }
while(<in1>) {
	chomp;
	if($_=~/^\>/) {
		my($id,$rest)=split(/\s+/,$_);
		$id=~s/^\>//;
		my @specs=($_=~/\[.*?\]/g);
		my $ms=join(" ",@specs);
		@{ $taxstore{$id} }=@specs;
		# print ">>$id>>$ms\n";
		}
	}
close in1;

my $clusterfile=$ARGV[1] || "nr_new.tsv";
print "Reading clusters in $clusterfile\n";
open(in2,$clusterfile) || die "Cannot open file $clusterfile\n";
while(<in2>) {
	chomp;
	my($ref,$map)=split(/\t/,$_);
	next if(!$taxstore{$map});
	my @atax=@{ $taxstore{$map} };
	# print "---@atax\n";
	map{ $accumtax{$ref}{$_}=1; } @atax;
	# print "*$map*$ref*\n";
	}
close in2;

my $filename="nr_clu_rep_cur.fasta";
print "Creating file $filename\n";
open(out,">$filename") || die;

my $nrfasta=$ARGV[3] || "nr_new.fasta";
print "Reading clusters in $nrfasta\n";
open(in3,$nrfasta) || die "Cannot open fasta file in $nrfasta\n";
while(<in3>) {
	chomp;
	if($_=~/^\>/) {
		my($id,$rest)=split(/\s+/,$_);
		$id=~s/^\>//;
		my @atax=keys %{ $accumtax{$id} };
		my $fulltax=join(" ",@atax);
		print out ">$id $fulltax\n";
		}
	else { print out "$_\n"; }
	}
close in3;
close out;

print "Output created in $filename\n";

	
