name: squeezemeta-dev_1.7.3.beta1
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python==3.12.11
  - setuptools==80.9.0
  - cython >=0.19.1
  - numpy >=1.9.0
  - scipy >=0.12.0
  - pandas >=0.11.0
  - biopython >=1.62b
  - scikit-learn >=0.18.0
  - nose >=1.3.0
  - gsl
  - samtools
  - blas=*=mkl
  - future
  - matplotlib
  - dendropy >=4.1.0
  - pysam
  - biopython
  - perl=5.32.1
  - perl-tie-ixhash
  - perl-dbd-mysql
  - perl-dbd-sqlite
  - perl-lwp-simple
  - perl-list-moreutils
  - perl-xml-libxml
  - perl-xml-parser
  - openjdk
  - ruby >=2.5
  - r-base==4.4.3
  - r-ggplot2
  - r-reshape2
  - r-doMC
  - r-data.table
  - r-zip
  - r-docopt
  - bioconductor-pathview
  - r-magick
  - r-ggpattern
  - tree
  - readline==8.2
  - krona
  - spades
  - mothur
  - kmer-db
  - metabat2
  - bowtie2
  - pplacer
  - prodigal
  - pydantic==2.11.7
  - mash
  - libopenblas
  - fasttree
  - hmmer
  - tqdm==4.67.1
  - skani
  - graph-tool
  - minimap2
  - mappy
  - python-igraph
  - fastani
  - nextflow
  - seqtk >=1.4
  - bedtools
  - vcflib >=1.0.1
  - picard
  - freebayes
  - checkm2
  - tensorflow
  - lightgbm
