{% set name = "squeezemeta-dev" %}
{% set version_match = load_file_regex(load_file = "../../VERSION",
                                       regex_pattern = '^[^,]*',
                                       from_recipe_dir = True) %}
{% set version = version_match[0] %}
{% set py_version = "3.12.11" %}
{% set pl_version = "5.32.1" %}
{% set r_version = "4.4.3" %}
{% set git_tag = "checkm2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  git_url: https://github.com/jtamames/squeezemeta.git
  git_tag: {{ git_tag }}
outputs:
  - name: {{ name|lower }}
    requirements:
      build:
        - python=={{ py_version }}
        - r-base=={{ r_version }}
        - r-ggplot2
        - r-reshape2
        - r-doMC
        - r-data.table
        - r-zip
        - bioconductor-pathview
        - perl={{ pl_version }}
        - perl-app-cpanminus
        - setuptools
        - cython >=0.19.1
        - numpy >=1.9.0
        - scipy >=0.12.0
        - pandas >=0.11.0
        - biopython >=1.62b
        - scikit-learn >=0.18.0
        - gsl
        - samtools
        - blas=*=mkl
        - readline=8
        - pydantic >=1.9.2,<2.0a1
        - tqdm >=4.35.0
        - dendropy >=4.1.0
        - graph-tool
        - mappy
        - python-igraph
      run:
        - python=={{ py_version }}
        - setuptools==80.9.0
        - cython==3.1.3
        - numpy==1.26.4
        - scipy==1.16.1
        - pandas==2.3.1
        - biopython==1.85
        - scikit-learn==1.6.1
        - gsl==2.7
        - samtools==1.22.1
        - blas==2.134
        - future==1.0.0
        - matplotlib==3.10.5
        - dendropy==5.0.8
        - pysam==0.23.3
        - biopython==1.85
        - perl={{ pl_version }}
        - perl-tie-ixhash==1.23
        - perl-dbd-mysql==5.013
        - perl-dbd-sqlite==1.76
        - perl-lwp-simple==6.67
        - perl-list-moreutils==0.430
        - perl-xml-libxml==2.0210
        - perl-xml-parser==2.44_01
        - openjdk==23.0.2
        - ruby==3.4.5
        - r-base=={{ r_version }}
        - r-ggplot2==3.5.2
        - r-reshape2==1.4.4
        - r-doMC
        - r-data.table==1.17.8
        - r-zip==2.3.3
        - bioconductor-pathview==1.46.0
        - tree==2.2.1
        - readline==8.2
        - krona==2.8.1
        - spades==4.2.0
        - mothur==1.48.3
        - kmer-db==2.3.1
        - metabat2==2.12.1
        - bowtie2==2.5.4
        - pplacer==1.1.alpha19
        - prodigal==2.6.3
        - pydantic==1.10.21
        - mash==2.3
        - libopenblas==0.3.30
        - fasttree==2.1.11
        - hmmer==3.4
        - tqdm==4.67.1
        - skani==0.3.0
        - graph-tool==2.77
        - minimap2==2.30
        - mappy==2.30
        - python-igraph==0.11.9
        - fastani==1.34
        - nextflow==25.04.6
        - seqtk==1.5
        - bedtools==2.31.1
        - vcflib==1.0.12
        - picard==3.4.0
        - freebayes==1.3.9
        - checkm2==1.1.0
        - tensorflow==2.17.0
        - lightgbm==4.6.0
        - absl-py==2.3.1
        - argcomplete==3.6.2
        - arpack==3.9.1
        - astunparse==1.6.3
        - at-spi2-atk==2.38.0
        - at-spi2-core==2.40.3
        - atk-1.0==2.38.0
        - bioconductor-annotationdbi==1.68.0
        - bioconductor-biobase==2.66.0
        - bioconductor-biocgenerics==0.52.0
        - bioconductor-biostrings==2.74.0
        - bioconductor-data-packages==20250625
        - bioconductor-genomeinfodb==1.42.0
        - bioconductor-genomeinfodbdata==1.2.13
        - bioconductor-graph==1.84.0
        - bioconductor-iranges==2.40.0
        - bioconductor-kegggraph==1.66.0
        - bioconductor-keggrest==1.46.0
        - bioconductor-org.hs.eg.db==3.20.0
        - bioconductor-rgraphviz==2.50.0
        - bioconductor-s4vectors==0.44.0
        - bioconductor-ucsc.utils==1.2.0
        - bioconductor-xvector==0.46.0
        - bioconductor-zlibbioc==1.52.0
        - blas-devel==3.9.0
        - boost-cpp==1.84.0
        - brotli==1.1.0
        - brotli-bin==1.1.0
        - brotli-python==1.1.0
        - bwidget==1.10.1
        - cached-property==1.5.2
        - cached_property==1.5.2
        - cairo==1.18.4
        - cairomm-1.16==1.16.2
        - capnproto==1.0.2
        - cffi==1.17.1
        - charset-normalizer==3.4.3
        - colorama==0.4.6
        - contourpy==1.3.3
        - coreutils==9.5
        - cycler==0.12.1
        - cyrus-sasl==2.1.28
        - diamond==2.1.11
        - double-conversion==3.3.1
        - epoxy==1.5.10
        - expat==2.7.1
        - fastahack==2016.07.2
        - flatbuffers==24.3.25
        - font-ttf-dejavu-sans-mono==2.37
        - font-ttf-inconsolata==3.000
        - font-ttf-source-code-pro==2.038
        - font-ttf-ubuntu==0.83
        - fontconfig==2.15.0
        - fonts-conda-ecosystem==1
        - fonts-conda-forge==1
        - fonttools==4.59.1
        - freetype==2.13.3
        - fribidi==1.0.10
        - gast==0.6.0
        - gdbm==1.18
        - gdk-pixbuf==2.42.12
        - giflib==5.2.2
        - glpk==5.0
        - gmp==6.3.0
        - google-pasta==0.2.0
        - graph-tool-base==2.77
        - graphite2==1.3.14
        - grpcio==1.65.5
        - gtk3==3.24.43
        - gxx_impl_linux-64==13.4.0
        - h2==4.2.0
        - h5py==3.13.0
        - harfbuzz==11.4.1
        - hdf5==1.14.3
        - hicolor-icon-theme==0.17
        - hpack==4.1.0
        - htslib==1.22.1
        - hyperframe==6.1.0
        - idna==3.10
        - importlib-metadata==8.7.0
        - joblib==1.5.1
        - jq==1.8.1
        - k8==1.2
        - keras==3.11.2
        - keyutils==1.6.3
        - kiwisolver==1.4.9
        - lcms2==2.17
        - libabseil==20240722.0
        - libaec==1.1.4
        - libasprintf==0.25.1
        - libblas==3.9.0
        - libboost==1.84.0
        - libboost-devel==1.84.0
        - libboost-headers==1.84.0
        - libboost-python==1.84.0
        - libbrotlicommon==1.1.0
        - libbrotlidec==1.1.0
        - libbrotlienc==1.1.0
        - libcblas==3.9.0
        - libclang-cpp20.1==20.1.8
        - libclang13==20.1.8
        - libcups==2.3.3
        - libdrm==2.4.125
        - libedit==3.1.20250104
        - libegl==1.7.0
        - libev==4.33
        - libexpat==2.7.1
        - libfreetype==2.13.3
        - libfreetype6==2.13.3
        - libgcc==15.1.0
        - libgcc-devel_linux-64==13.4.0
        - libgcc-ng==15.1.0
        - libgettextpo==0.25.1
        - libgfortran==15.1.0
        - libgfortran-ng==15.1.0
        - libgfortran5==15.1.0
        - libgirepository==1.84.0
        - libgl==1.7.0
        - libglib==2.84.3
        - libglvnd==1.7.0
        - libglx==1.7.0
        - libgomp==15.1.0
        - libgrpc==1.65.5
        - libhwloc==2.12.1
        - libiconv==1.18
        - libidn2==2.3.8
        - libjpeg-turbo==3.1.0
        - liblapack==3.9.0
        - liblapacke==3.9.0
        - liblightgbm==4.6.0
        - libllvm20==20.1.8
        - liblzma==5.8.1
        - libnghttp2==1.64.0
        - libnsl==2.0.1
        - libntlm==1.8
        - libopengl==1.7.0
        - libpciaccess==0.18
        - libpng==1.6.50
        - libprotobuf==5.27.5
        - libre2-11==2024.07.02
        - librsvg==2.58.4
        - libsanitizer==13.4.0
        - libsqlite==3.50.4
        - libssh2==1.11.1
        - libstdcxx==15.1.0
        - libstdcxx-devel_linux-64==13.4.0
        - libstdcxx-ng==15.1.0
        - libtiff==4.7.0
        - libunistring==0.9.10
        - libwebp-base==1.6.0
        - libxcrypt==4.4.36
        - libxslt==1.1.43
        - libzlib==1.3.1
        - llvm-openmp==20.1.8
        - make==4.4.1
        - markdown==3.8.2
        - markdown-it-py==4.0.0
        - markupsafe==3.0.2
        - matplotlib-base==3.10.5
        - mdurl==0.1.2
        - mkl==2024.2.2
        - mkl-devel==2024.2.2
        - mkl-include==2024.2.2
        - ml_dtypes==0.4.0
        - mpi==1.0
        - munkres==1.1.4
        - mysql==5.7.20
        - mysql-common==8.4.2
        - mysql-libs==8.4.2
        - namex==0.1.0
        - ncbi-vdb==3.2.1
        - ncurses==6.5
        - ocl-icd==2.3.3
        - oniguruma==6.9.10
        - opencl-headers==2025.06.13
        - openjpeg==2.5.3
        - openldap==2.6.10
        - openmpi==4.1.6
        - opt_einsum==3.4.0
        - optree==0.17.0
        - ossuuid==1.6.2
        - packaging==25.0
        - pango==1.56.4
        - parallel==20250622
        - pcre2==10.45
        - perl-alien-build==2.84
        - perl-alien-libxml2==0.17
        - perl-b-cow==0.007
        - perl-base==2.23
        - perl-business-isbn==3.007
        - perl-business-isbn-data==20210112.006
        - perl-capture-tiny==0.48
        - perl-carp==1.50
        - perl-clone==0.46
        - perl-compress-raw-bzip2==2.201
        - perl-compress-raw-zlib==2.202
        - perl-constant==1.33
        - perl-dbi==1.643
        - perl-devel-checklib==1.16
        - perl-digest-hmac==1.04
        - perl-digest-md5==2.59
        - perl-encode==3.21
        - perl-encode-locale==1.05
        - perl-exporter==5.74
        - perl-exporter-tiny==1.002002
        - perl-extutils-makemaker==7.70
        - perl-ffi-checklib==0.28
        - perl-file-chdir==0.1011
        - perl-file-listing==6.16
        - perl-file-path==2.18
        - perl-file-spec==3.48_01
        - perl-file-temp==0.2304
        - perl-file-which==1.24
        - perl-html-parser==3.83
        - perl-html-tagset==3.24
        - perl-http-cookies==6.11
        - perl-http-daemon==6.16
        - perl-http-date==6.06
        - perl-http-message==7.00
        - perl-http-negotiate==6.01
        - perl-importer==0.026
        - perl-io-html==1.004
        - perl-io-socket-ssl==2.075
        - perl-libwww-perl==6.67
        - perl-list-moreutils-xs==0.430
        - perl-lwp-mediatypes==6.04
        - perl-mime-base64==3.16
        - perl-net-http==6.22
        - perl-net-ssleay==1.94
        - perl-ntlm==1.09
        - perl-parent==0.243
        - perl-path-tiny==0.124
        - perl-pathtools==3.75
        - perl-scope-guard==0.21
        - perl-socket==2.027
        - perl-storable==3.15
        - perl-sub-info==0.002
        - perl-term-table==0.024
        - perl-test-fatal==0.016
        - perl-test-needs==0.002009
        - perl-test-warnings==0.031
        - perl-test2-suite==0.000163
        - perl-time-hires==1.9764
        - perl-time-local==1.35
        - perl-timedate==2.33
        - perl-try-tiny==0.32
        - perl-uri==5.17
        - perl-url-encode==0.03
        - perl-www-robotrules==6.02
        - perl-xml-namespacesupport==1.12
        - perl-xml-sax==1.02
        - perl-xml-sax-base==1.09
        - pillow==11.3.0
        - pip==25.2
        - pixman==0.46.4
        - protobuf==5.27.5
        - pthread-stubs==0.4
        - pycairo==1.28.0
        - pycparser==2.22
        - pygments==2.19.2
        - pygobject==3.50.0
        - pyparsing==3.2.3
        - pyside6==6.9.1
        - pysocks==1.7.1
        - python-dateutil==2.9.0.post0
        - python-flatbuffers==25.2.10
        - python-tzdata==2025.2
        - pytz==2025.2
        - pyyaml==6.0.2
        - qhull==2020.2
        - qt6-main==6.9.1
        - r-askpass==1.2.1
        - r-bit==4.6.0
        - r-bit64==4.6.0_1
        - r-bitops==1.0_9
        - r-blob==1.2.4
        - r-cachem==1.1.0
        - r-cli==3.6.5
        - r-codetools==0.2_20
        - r-colorspace==2.1_1
        - r-cpp11==0.5.2
        - r-crayon==1.5.3
        - r-curl==6.4.0
        - r-dbi==1.2.3
        - r-domc==1.3.8
        - r-ellipsis==0.3.2
        - r-fansi==1.0.6
        - r-farver==2.1.2
        - r-fastmap==1.2.0
        - r-foreach==1.5.2
        - r-glue==1.8.0
        - r-gtable==0.3.6
        - r-httr==1.4.7
        - r-isoband==0.2.7
        - r-iterators==1.0.14
        - r-jsonlite==2.0.0
        - r-labeling==0.4.3
        - r-lattice==0.22_7
        - r-lifecycle==1.0.4
        - r-magrittr==2.0.3
        - r-mass==7.3_64
        - r-matrix==1.7_3
        - r-memoise==2.0.1
        - r-mgcv==1.9_3
        - r-mime==0.13
        - r-munsell==0.5.1
        - r-nlme==3.1_168
        - r-openssl==2.3.3
        - r-pillar==1.11.0
        - r-pkgconfig==2.0.3
        - r-plogr==0.2.0
        - r-plyr==1.8.9
        - r-png==0.1_8
        - r-r6==2.6.1
        - r-rcolorbrewer==1.1_3
        - r-rcpp==1.1.0
        - r-rcurl==1.98_1.17
        - r-rlang==1.1.6
        - r-rsqlite==2.4.2
        - r-scales==1.4.0
        - r-stringi==1.8.7
        - r-stringr==1.5.1
        - r-sys==3.4.3
        - r-tibble==3.3.0
        - r-utf8==1.2.6
        - r-vctrs==0.6.5
        - r-viridislite==0.4.2
        - r-withr==3.0.2
        - r-xml==3.99_0.17
        - re2==2024.07.02
        - requests==2.32.4
        - rich==14.1.0
        - sed==4.9
        - sigcpp-3.0==3.6.0
        - six==1.17.0
        - snappy==1.2.2
        - sparsehash==2.0.4
        - sra-tools==3.2.1
        - tabixpp==1.1.2
        - tbb==2021.13.0
        - tensorboard==2.17.1
        - tensorboard-data-server==0.7.0
        - tensorflow-base==2.17.0
        - tensorflow-estimator==2.17.0
        - termcolor==3.1.0
        - texttable==1.7.0
        - threadpoolctl==3.6.0
        - tk==8.6.13
        - tktable==2.10
        - toml==0.10.2
        - tomlkit==0.13.3
        - tornado==6.5.2
        - typing-extensions==4.14.1
        - typing_extensions==4.14.1
        - tzdata==2025b
        - unicodedata2==16.0.0
        - urllib3==2.5.0
        - vsearch==2.30.0
        - wayland==1.24.0
        - werkzeug==3.1.3
        - wget==1.21.4
        - wheel==0.45.1
        - wrapt==1.17.3
        - xcb-util==0.4.1
        - xcb-util-cursor==0.1.5
        - xcb-util-image==0.4.0
        - xcb-util-keysyms==0.4.1
        - xcb-util-renderutil==0.3.10
        - xcb-util-wm==0.4.2
        - xkeyboard-config==2.45
        - xmltodict==0.14.2
        - xorg-libice==1.1.2
        - xorg-libsm==1.2.6
        - xorg-libx11==1.8.12
        - xorg-libxau==1.0.12
        - xorg-libxcomposite==0.4.6
        - xorg-libxcursor==1.2.3
        - xorg-libxdamage==1.1.6
        - xorg-libxdmcp==1.1.5
        - xorg-libxext==1.3.6
        - xorg-libxfixes==6.0.1
        - xorg-libxi==1.8.2
        - xorg-libxinerama==1.1.5
        - xorg-libxrandr==1.5.4
        - xorg-libxrender==0.9.12
        - xorg-libxt==1.3.1
        - xorg-libxtst==1.2.5
        - xorg-libxxf86vm==1.1.6
        - yaml==0.2.5
        - yq==3.4.3
        - zipp==3.23.0
        - zlib==1.3.1
        - zstandard==0.23.0
    build:
      noarch: generic
    test:
      command: cd $PREFIX/SqueezeMeta/scripts; for script in *.pl; do perl -c $script;
        done; perl $PREFIX/SqueezeMeta/utils/install_utils/test_install.pl

about:
  home:  https://github.com/jtamames/SqueezeMeta
  license: GPL-3
  license_file: ../../LICENSE
  summary: 'SqueezeMeta: a fully automated metagenomics pipeline, from reads to bins'
  description:
          "SqueezeMeta is a fully automatic pipeline for metagenomics/metatranscriptomics,
          covering all steps of the analysis. SqueezeMeta includes multi-metagenome
          support allowing the co-assembly of related metagenomes and the retrieval of
          individual genomes via binning procedures.
          \n
          \n
          To install this package with mamba run:
          \n
          \n
          `mamba create -n SqueezeMeta -c conda-forge -c bioconda -c fpusan {{ name }} --no-channel-priority --override-channels`
          \n
          \n
          And activate it with:
          \n
          \n
          `conda activate SqueezeMeta`
          \n
          \n
          Detailed usage instructions can be found at <http://github.com/jtamames/SqueezeMeta>"
  dev_url: https://github.com/jtamames/SqueezeMeta
  doc_url: https://github.com/jtamames/SqueezeMeta
  doc_source_url: https://github.com/jtamames/SqueezeMeta/blob/master/README.md
  recipe-maintainers:
    - fpusan

