package:
  name: squeezemeta
  version: "1.7.3.alpha1"

source:
  git_url: https://github.com/jtamames/squeezemeta.git
  git_tag: checkm2

requirements:
  build:
    - python==3.12.11
    - r-base==4.1.3
    - r-ggplot2
    - r-reshape2
    - r-doMC
    - r-data.table
    - r-zip
    - bioconductor-pathview
    - perl=5.32.1
    - perl-app-cpanminus
    - setuptools
    - cython >=0.19.1
    - numpy >=1.9.0
    - scipy >=0.12.0
    - pandas >=0.11.0
    - biopython >=1.62b
    - scikit-learn >=0.18.0
    - nose >=1.3.0
    - gsl
    - samtools
    - blas=*=mkl # To avoid openmp
    - readline=8
    - pydantic >=1.9.2,<2.0a1 # Add gtdb-tk, mOTUlizer and superpang python reqs in build
    - tqdm >=4.35.0           #  since they will be installed with pip but we'd rather have their deps installed through conda
    - dendropy >=4.1.0
    - graph-tool
    - mappy
    - python-igraph
      #- igraph==0.10.8 # Required by mOTUlizer but missing in conda apparently
  run:
    - python==3.12.11
    - setuptools
    - cython >=0.19.1
    - numpy >=1.9.0
    - scipy >=0.12.0
    - pandas >=0.11.0
    - biopython >=1.62b
    - scikit-learn >=0.18.0
    - nose >=1.3.0
    - gsl # last time I checked we need v2.7 from conda-forge (the one from anaconda will fail)
    - samtools
    - blas=*=mkl # To avoid openblas which causes trouble with CONCOCT
    - future
    - matplotlib
    - dendropy >=4.1.0
    - pysam
    - biopython
    - perl=5.32.1
    - perl-tie-ixhash
    - perl-dbd-mysql
    - perl-dbd-sqlite
    - perl-lwp-simple
    - perl-list-moreutils
    - perl-xml-libxml
    - perl-xml-parser
    - openjdk
    - ruby >=2.5
    - r-base >=4.1.3
    - r-ggplot2
    - r-reshape2
    - r-doMC
    - r-data.table
    - r-zip
    - bioconductor-pathview
    - tree
    - readline=8
    - krona
    # SQUEEZEMETA BINARIES
    - spades
    - mothur
    - kmer-db
    - metabat2
    - bowtie2
    # GTDBTK
    - pplacer
    - prodigal
    - pydantic >=1.9.2,<2.0a1
    - mash
    - libopenblas
    - fasttree
    - hmmer
    - tqdm >=4.35.0
    - skani
    # SUPERPANG/mOTUlizer
    - graph-tool
    - minimap2
    - mappy
    #- igraph==0.10.8 # Required by mOTUlizer but missing in conda apparently, should get installed during build
    - python-igraph
    - fastani
    # PANGENOME PIPELINE
    - nextflow
    - seqtk >=1.4
    - bedtools
    # POGENOM
    - vcflib >=1.0.1
    - picard
    - freebayes
    # CHECKM2
    - checkm2
    - tensorflow
    - lightgbm

build:
  noarch: generic

test:
  command: "cd $PREFIX/SqueezeMeta/scripts; for script in *.pl; do perl -c $script; done; perl $PREFIX/SqueezeMeta/utils/install_utils/test_install.pl"

about:
  home:  https://github.com/jtamames/SqueezeMeta
  license: GPL-3
  license_file: ../../LICENSE
  summary: 'SqueezeMeta: a fully automated metagenomics pipeline, from reads to bins'
  description:
          "SqueezeMeta is a fully automatic pipeline for metagenomics/metatranscriptomics,
          covering all steps of the analysis. SqueezeMeta includes multi-metagenome
          support allowing the co-assembly of related metagenomes and the retrieval of
          individual genomes via binning procedures.
          \n
          \n
          To install this package with mamba run:
          \n
          \n
          `mamba create -n SqueezeMeta -c conda-forge -c bioconda -c fpusan squeezemeta --no-channel-priority --override-channels`
          \n
          \n
          And activate it with:
          \n
          \n
          `conda activate SqueezeMeta`
          \n
          \n
          Detailed usage instructions can be found at <http://github.com/jtamames/SqueezeMeta>"
  dev_url: https://github.com/jtamames/SqueezeMeta
  doc_url: https://github.com/jtamames/SqueezeMeta
  doc_source_url: https://github.com/jtamames/SqueezeMeta/blob/master/README.md
  recipe-maintainers:
      - fpusan
