package:
  name: squeezemeta-dev
  version: "1.6.3.beta2"

source:
  git_url: https://github.com/jtamames/squeezemeta.git
  git_tag: master

requirements:
  build:
    - python==3.10
    - r=3.6
    - r-ggplot2
    - r-reshape2
    - r-doMC
    - r-data.table
    - bioconductor-pathview
    - perl=5.26
    - perl-app-cpanminus
    - setuptools
    - cython >=0.19.1
    - numpy==1.25.0
    - scipy >=0.12.0
    - pandas >=0.11.0
    - biopython >=1.62b
    - scikit-learn >=0.18.0
    - nose >=1.3.0
    - gsl
    - openmp
    - samtools==1.11
    - blas=*=mkl # To avoid openmp
    - readline=8
  run:
    # Packages originally specified in the template
    - python==3.10.2
    - setuptools==68.1.2
    - cython >=0.19.1
    - numpy==1.25.2
    - scipy >=0.12.0
    - pandas >=0.11.0
    - biopython >=1.62b
    - scikit-learn >=0.18.0
    - nose >=1.3.0
    - gsl==2.6
    - openmp==8.0.1
    - samtools==1.11
    - blas==1.0
    - future==0.18.3
    - matplotlib==3.7.2
    - dendropy==4.6.1
    - pysam==0.20.0
    - biopython==1.81
    - perl==5.26.2
    - perl-tie-ixhash==1.23
    - perl-dbd-mysql==4.046
    - perl-dbd-sqlite==1.64
    - perl-lwp-simple==6.15
    - perl-xml-libxml==2.0132
    - perl-xml-parser==2.44_01
    - openjdk==11.0.9.1
    - ruby==2.5.7
    - r==3.6
    - r-ggplot2==3.3.3
    - r-reshape2==1.4.4
    - r-doMC
    - r-data.table==1.14.0
    - bioconductor-pathview==1.26.0
    - tree==2.1.1
    - readline==8.1
    - krona==2.8.1
    # Extra dependencies
    - _sysroot_linux-64_curr_repodata_hack==3
    - bioconductor-annotationdbi==1.48.0
    - bioconductor-biobase==2.46.0
    - bioconductor-biocgenerics==0.32.0
    - bioconductor-biostrings==2.54.0
    - bioconductor-graph==1.64.0
    - bioconductor-iranges==2.20.0
    - bioconductor-kegggraph==1.46.0
    - bioconductor-keggrest==1.26.0
    - bioconductor-org.hs.eg.db==3.10.0
    - bioconductor-rgraphviz==2.30.0
    - bioconductor-s4vectors==0.24.0
    - bioconductor-xvector==0.26.0
    - bioconductor-zlibbioc==1.32.0
    - blast-legacy==2.2.26
    - boost-cpp==1.74.0
    - brotli==1.1.0
    - brotli-bin==1.1.0
    - brotli-python==1.1.0
    - bwidget==1.9.14
    - cairo==1.16.0
    - charset-normalizer==3.2.0
    - contourpy==1.1.0
    - cycler==0.11.0
    - cython==3.0.2
    - expat==2.5.0
    - font-ttf-dejavu-sans-mono==2.37
    - font-ttf-inconsolata==3.000
    - font-ttf-source-code-pro==2.038
    - font-ttf-ubuntu==0.83
    - fontconfig==2.14.2
    - fonts-conda-ecosystem==1
    - fonts-conda-forge==1
    - fonttools==4.42.1
    - freetype==2.12.1
    - fribidi==1.0.10
    - gdbm==1.18
    - gettext==0.21.1
    - giflib==5.2.1
    - gmp==6.2.1
    - graphite2==1.3.13
    - gst-plugins-base==1.18.5
    - gstreamer==1.18.5
    - gxx_impl_linux-64==9.5.0
    - gxx_linux-64==9.5.0
    - harfbuzz==2.9.1
    - hdf5==1.10.6
    - htslib==1.11
    - idna==3.4
    - intel-openmp==2022.1.0
    - joblib==1.3.2
    - jpeg==9e
    - kernel-headers_linux-64==3.10.0
    - keyutils==1.6.1
    - kiwisolver==1.4.5
    - kmer-db==1.11.1
    - lcms2==2.14
    - ld_impl_linux-64==2.39
    - libblas==3.9.0
    - libbrotlicommon==1.1.0
    - libbrotlidec==1.1.0
    - libbrotlienc==1.1.0
    - libcblas==3.9.0
    - libclang==11.1.0
    - libedit==3.1.20191231
    - libev==4.33
    - libevent==2.1.10
    - libexpat==2.5.0
    - libgcc-devel_linux-64==9.5.0
    - libgcc-ng==13.1.0
    - libgfortran-ng==13.1.0
    - libgfortran5==13.1.0
    - libglib==2.76.4
    - libgomp==13.1.0
    - libiconv==1.17
    - liblapack==3.9.0
    - libllvm11==11.1.0
    - libnghttp2==1.51.0
    - libnsl==2.0.0
    - libogg==1.3.4
    - libopenblas==0.3.24
    - libopus==1.3.1
    - libpng==1.6.39
    - libsanitizer==9.5.0
    - libsqlite==3.43.0
    - libssh2==1.10.0
    - libstdcxx-devel_linux-64==9.5.0
    - libstdcxx-ng==13.1.0
    - libtiff==4.4.0
    - libvorbis==1.3.7
    - libwebp==1.2.4
    - libwebp-base==1.2.4
    - libzlib==1.2.13
    - llvm-openmp==8.0.1
    - make==4.3
    - matplotlib-base==3.7.2
    - metabat2==2.12.1
    - mkl==2022.1.0
    - mothur==1.47.0
    - munkres==1.1.4
    - mysql-common==8.0.32
    - mysql-connector-c==6.1.11
    - mysql-libs==8.0.32
    - ncbi-vdb==3.0.7
    - ncurses==6.2
    - nose==1.3.7
    - nspr==4.35
    - nss==3.92
    - openblas==0.3.24
    - ossuuid==1.6.2
    - packaging==23.1
    - pandas==2.1.0
    - pango==1.48.10
    - pcre==8.45
    - pcre2==10.40
    - perl-app-cpanminus==1.7044
    - perl-business-isbn==3.004
    - perl-business-isbn-data==20140910.003
    - perl-carp==1.38
    - perl-constant==1.33
    - perl-data-dumper==2.173
    - perl-dbi==1.642
    - perl-encode==2.88
    - perl-encode-locale==1.05
    - perl-exporter==5.72
    - perl-extutils-makemaker==7.36
    - perl-file-path==2.16
    - perl-file-temp==0.2304
    - perl-mime-base64==3.15
    - perl-parent==0.236
    - perl-uri==1.76
    - perl-xml-namespacesupport==1.12
    - perl-xml-sax==1.02
    - perl-xml-sax-base==1.09
    - perl-xsloader==0.24
    - pillow==9.3.0
    - pip==23.2.1
    - pixman==0.40.0
    - platformdirs==3.10.0
    - pooch==1.7.0
    - pthread-stubs==0.4
    - pyparsing==3.0.9
    - pyqt==5.12.3
    - pyqt-impl==5.12.3
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-tzdata==2023.3
    - pytz==2023.3.post1
    - qt==5.12.9
    - r-askpass==1.1
    - r-assertthat==0.2.1
    - r-backports==1.2.1
    - r-base==3.6.3
    - r-bit==4.0.4
    - r-bit64==4.0.5
    - r-bitops==1.0_7
    - r-blob==1.2.1
    - r-boot==1.3_28
    - r-brio==1.1.2
    - r-cachem==1.0.5
    - r-callr==3.7.0
    - r-class==7.3_19
    - r-cli==2.5.0
    - r-cluster==2.1.2
    - r-codetools==0.2_18
    - r-colorspace==2.0_1
    - r-crayon==1.4.1
    - r-curl==4.3.1
    - r-dbi==1.1.1
    - r-desc==1.3.0
    - r-diffobj==0.3.4
    - r-digest==0.6.27
    - r-domc==1.3.7
    - r-ellipsis==0.3.2
    - r-evaluate==0.14
    - r-fansi==0.4.2
    - r-farver==2.1.0
    - r-fastmap==1.1.0
    - r-foreach==1.5.1
    - r-foreign==0.8_76
    - r-glue==1.4.2
    - r-gtable==0.3.0
    - r-httr==1.4.2
    - r-isoband==0.2.4
    - r-iterators==1.0.13
    - r-jsonlite==1.7.2
    - r-kernsmooth==2.23_20
    - r-labeling==0.4.2
    - r-lattice==0.20_44
    - r-lifecycle==1.0.0
    - r-magrittr==2.0.1
    - r-mass==7.3_54
    - r-matrix==1.3_3
    - r-memoise==2.0.0
    - r-mgcv==1.8_35
    - r-mime==0.10
    - r-munsell==0.5.0
    - r-nlme==3.1_152
    - r-nnet==7.3_16
    - r-openssl==1.4.4
    - r-pillar==1.6.1
    - r-pkgconfig==2.0.3
    - r-pkgload==1.2.1
    - r-plogr==0.2.0
    - r-plyr==1.8.6
    - r-png==0.1_7
    - r-praise==1.0.0
    - r-processx==3.5.2
    - r-ps==1.6.0
    - r-r6==2.5.0
    - r-rcolorbrewer==1.1_2
    - r-rcpp==1.0.6
    - r-rcurl==1.98_1.3
    - r-recommended==3.6
    - r-rematch2==2.1.2
    - r-rlang==0.4.11
    - r-rpart==4.1_15
    - r-rprojroot==2.0.2
    - r-rsqlite==2.2.5
    - r-rstudioapi==0.13
    - r-scales==1.1.1
    - r-spatial==7.3_14
    - r-stringi==1.6.2
    - r-stringr==1.4.0
    - r-survival==3.2_11
    - r-sys==3.4
    - r-testthat==3.0.2
    - r-tibble==3.1.2
    - r-utf8==1.2.1
    - r-vctrs==0.3.8
    - r-viridislite==0.4.0
    - r-waldo==0.2.5
    - r-withr==2.4.2
    - r-xml==3.99_0.3
    - requests==2.31.0
    - scikit-learn==1.3.0
    - scipy==1.11.2
    - sed==4.8
    - six==1.16.0
    - spades==3.15.5
    - sqlite==3.37.0
    - sra-tools==3.0.7
    - threadpoolctl==3.2.0
    - tk==8.6.12
    - tktable==2.10
    - tornado==6.3.3
    - typing-extensions==4.7.1
    - typing_extensions==4.7.1
    - tzdata==2023c
    - unicodedata2==15.0.0
    - urllib3==2.0.4
    - vsearch==2.15.2
    - wheel==0.41.2
    - xorg-fixesproto==5.0
    - xorg-inputproto==2.3.2
    - xorg-kbproto==1.0.7
    - xorg-libice==1.1.1
    - xorg-libsm==1.2.4
    - xorg-libx11==1.8.6
    - xorg-libxau==1.0.11
    - xorg-libxdmcp==1.1.3
    - xorg-libxext==1.3.4
    - xorg-libxfixes==5.0.3
    - xorg-libxi==1.7.10
    - xorg-libxrender==0.9.11
    - xorg-libxtst==1.2.3
    - xorg-recordproto==1.14.2
    - xorg-renderproto==0.11.1
    - xorg-xextproto==7.3.0
    - xorg-xproto==7.0.31
    - yaml==0.2.5
    - zlib==1.2.13

build:
  noarch: generic

test:
  command: "cd $PREFIX/SqueezeMeta/scripts; for script in *.pl; do perl -c $script; done; perl $PREFIX/SqueezeMeta/utils/install_utils/test_install.pl"

about:
  home:  https://github.com/jtamames/SqueezeMeta
  license: GPL-3
  license_file: ../../LICENSE
  summary: 'SqueezeMeta: a fully automated metagenomics pipeline, from reads to bins'
  description:
          "SqueezeMeta is a fully automatic pipeline for metagenomics/metatranscriptomics,
          covering all steps of the analysis. SqueezeMeta includes multi-metagenome
          support allowing the co-assembly of related metagenomes and the retrieval of
          individual genomes via binning procedures.
          \n
          \n
          To install this package with mamba run:
          \n
          \n
          `mamba create -n SqueezeMeta -c conda-forge -c bioconda -c anaconda -c fpusan squeezemeta-dev --no-channel-priority`
          \n
          \n
          And activate it with:
          \n
          \n
          `conda activate SqueezeMeta`
          \n
          \n
          Detailed usage instructions can be found at <http://github.com/jtamames/SqueezeMeta>"
  dev_url: https://github.com/jtamames/SqueezeMeta
  doc_url: https://github.com/jtamames/SqueezeMeta
  doc_source_url: https://github.com/jtamames/SqueezeMeta/blob/master/README.md
  recipe-maintainers:
      - fpusan
