package:
  name: squeezemeta-dev
  version: "1.7.1.beta2"

source:
  git_url: https://github.com/jtamames/squeezemeta.git
  git_tag: develop

requirements:
  build:
    - python==3.10
    - r-base==4.1.3
    - r-ggplot2
    - r-reshape2
    - r-doMC
    - r-data.table
    - r-zip
    - bioconductor-pathview
    - perl=5.26
    - perl-app-cpanminus
    - setuptools
    - cython >=0.19.1
    - numpy >=1.9.0
    - scipy >=0.12.0
    - pandas >=0.11.0
    - biopython >=1.62b
    - scikit-learn >=0.18.0
    - nose >=1.3.0
    - gsl
    - samtools
    - blas=*=mkl # To avoid openmp
    - readline=8
    - pydantic >=1.9.2,<2.0a1 # Add gtdb-tk, mOTUlizer and superpang python reqs in build
    - tqdm >=4.35.0           #  since they will be installed with pip but we'd rather have their deps installed through conda
    - dendropy >=4.1.0
    - graph-tool
    - mappy
    - python-igraph
      #- igraph==0.10.8 # Required by mOTUlizer but missing in conda apparently
  run:
    # Packages originally specified in the template
    - python==3.10.0
    - setuptools==75.6.0
    - cython >=0.19.1
    - numpy==1.26.4
    - scipy >=0.12.0
    - pandas >=0.11.0
    - biopython >=1.62b
    - scikit-learn >=0.18.0
    - nose >=1.3.0
    - gsl # last time I checked we need v2.7 from conda-forge (the one from anaconda will fail)
    - samtools==1.16.1
    - blas==2.125
    - future==1.0.0
    - matplotlib==3.9.1
    - dendropy >=4.1.0
    - pysam==0.20.0
    - biopython==1.84
    - perl==5.26.2
    - perl-tie-ixhash==1.23
    - perl-dbd-mysql==4.046
    - perl-dbd-sqlite==1.64
    - perl-lwp-simple==6.15
    - perl-list-moreutils==0.428
    - perl-xml-libxml==2.0132
    - perl-xml-parser==2.44_01
    - openjdk==17.0.3
    - ruby==2.5.7
    - r-base==4.1.3
    - r-ggplot2==3.4.2
    - r-reshape2==1.4.4
    - r-doMC
    - r-data.table==1.14.8
    - r-zip==2.3.0
    - bioconductor-pathview==1.34.0
    - tree==2.1.3
    - readline==8.2
    - krona==2.8.1
    # SQUEEZEMETA BINARIES
    - spades==4.0.0
    - mothur==1.48.0
    - kmer-db==2.2.5
    - metabat2==2.15
    - bowtie2==2.5.4
    # GTDBTK
    - pplacer==1.1.alpha19
    - prodigal==2.6.3
    - pydantic >=1.9.2,<2.0a1
    - mash==2.3
    - libopenblas==0.3.28
    - fasttree==2.1.11
    - hmmer==3.4
    - tqdm >=4.35.0
    - skani==0.2.2
    # SUPERPANG/mOTUlizer
    - graph-tool==2.45
    - minimap2==2.28
    - mappy==2.28
    #- igraph==0.10.8 # Required by mOTUlizer but missing in conda apparently, should get installed during build
    - python-igraph==0.10.2
    - fastani==1.34
    # PANGENOME PIPELINE
    - nextflow==24.10.2
    - seqtk >=1.4
    - bedtools==2.31.1
    # POGENOM
    - vcflib==1.0.1
    - picard==3.3.0
    - freebayes==1.3.6
    # CHECKM2
    - tensorflow==2.11.0
    - lightgbm==4.5.0
    - diamond==2.0.15
    # Extra dependencies
    - absl-py==2.1.0
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.9
    - aiosignal==1.3.1
    - arpack==3.7.0
    - astunparse==1.6.3
    - async-timeout==5.0.1
    - at-spi2-atk==2.38.0
    - at-spi2-core==2.40.3
    - atk-1.0==2.38.0
    - attr==2.5.1
    - attrs==24.2.0
    - bc==1.07.1
    - bioconductor-annotationdbi==1.56.2
    - bioconductor-biobase==2.54.0
    - bioconductor-biocgenerics==0.40.0
    - bioconductor-biostrings==2.62.0
    - bioconductor-genomeinfodb==1.30.1
    - bioconductor-genomeinfodbdata==1.2.7
    - bioconductor-graph==1.72.0
    - bioconductor-iranges==2.28.0
    - bioconductor-kegggraph==1.54.0
    - bioconductor-keggrest==1.34.0
    - bioconductor-org.hs.eg.db==3.14.0
    - bioconductor-rgraphviz==2.38.0
    - bioconductor-s4vectors==0.32.4
    - bioconductor-xvector==0.34.0
    - bioconductor-zlibbioc==1.40.0
    - blas-devel==3.9.0
    - blast-legacy==2.2.26
    - blinker==1.9.0
    - boost==1.74.0
    - boost-cpp==1.74.0
    - brotli==1.1.0
    - brotli-bin==1.1.0
    - brotli-python==1.1.0
    - bwidget==1.9.14
    - cached-property==1.5.2
    - cached_property==1.5.2
    - cachetools==5.5.0
    - cairo==1.16.0
    - cairomm==1.14.4
    - cairomm-1.0==1.14.4
    - capnproto==1.0.2
    - cffi==1.17.1
    - charset-normalizer==3.4.0
    - click==8.1.7
    - colorama==0.4.6
    - contourpy==1.3.1
    - coreutils==9.5
    - cryptography==39.0.0
    - cuda-version==11.8
    - cudatoolkit==11.8.0
    - cudnn==8.9.7.29
    - cycler==0.12.1
    - cython==3.0.11
    - dendropy==5.0.1
    - epoxy==1.5.10
    - expat==2.6.4
    - fftw==3.3.10
    - flatbuffers==22.12.06
    - font-ttf-dejavu-sans-mono==2.37
    - font-ttf-inconsolata==3.000
    - font-ttf-source-code-pro==2.038
    - font-ttf-ubuntu==0.83
    - fontconfig==2.14.2
    - fonts-conda-ecosystem==1
    - fonts-conda-forge==1
    - fonttools==4.55.0
    - freetype==2.12.1
    - fribidi==1.0.10
    - frozenlist==1.5.0
    - gast==0.4.0
    - gdbm==1.18
    - gdk-pixbuf==2.42.8
    - gettext==0.22.5
    - gettext-tools==0.22.5
    - giflib==5.2.2
    - glpk==5.0
    - gmp==6.3.0
    - google-auth==2.36.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - graph-tool-base==2.45
    - graphite2==1.3.13
    - grpcio==1.51.1
    - gsl==2.7
    - gst-plugins-base==1.20.3
    - gstreamer==1.20.3
    - gtk3==3.24.35
    - gxx_impl_linux-64==14.2.0
    - h2==4.1.0
    - h5py==3.7.0
    - harfbuzz==5.3.0
    - hdf5==1.12.1
    - hicolor-icon-theme==0.17
    - hpack==4.0.0
    - htslib==1.16
    - hyperframe==6.0.1
    - idna==3.10
    - importlib-metadata==8.5.0
    - jack==1.9.21
    - joblib==1.4.2
    - jpeg==9e
    - k8==0.2.5
    - keras==2.11.0
    - keras-preprocessing==1.1.2
    - kernel-headers_linux-64==3.10.0
    - keyutils==1.6.1
    - kiwisolver==1.4.7
    - lame==3.100
    - lcms2==2.14
    - ld_impl_linux-64==2.43
    - libabseil==20220623.0
    - libasprintf==0.22.5
    - libasprintf-devel==0.22.5
    - libblas==3.9.0
    - libbrotlicommon==1.1.0
    - libbrotlidec==1.1.0
    - libbrotlienc==1.1.0
    - libcap==2.66
    - libcblas==3.9.0
    - libclang==14.0.6
    - libclang13==14.0.6
    - libcups==2.3.3
    - libdb==6.2.32
    - libedit==3.1.20191231
    - libev==4.33
    - libevent==2.1.10
    - libexpat==2.6.4
    - libflac==1.4.3
    - libgcc==14.2.0
    - libgcc-devel_linux-64==14.2.0
    - libgcc-ng==14.2.0
    - libgettextpo==0.22.5
    - libgettextpo-devel==0.22.5
    - libgfortran==14.2.0
    - libgfortran-ng==14.2.0
    - libgfortran5==14.2.0
    - libgirepository==1.74.0
    - libglib==2.74.1
    - libgomp==14.2.0
    - libgrpc==1.51.1
    - libhwloc==2.8.0
    - libiconv==1.17
    - liblapack==3.9.0
    - liblapacke==3.9.0
    - liblightgbm==4.5.0
    - libllvm14==14.0.6
    - libnghttp2==1.51.0
    - libnsl==2.0.1
    - libogg==1.3.5
    - libopus==1.3.1
    - libpng==1.6.43
    - libprotobuf==3.21.12
    - librsvg==2.54.4
    - libsanitizer==14.2.0
    - libsndfile==1.1.0
    - libsqlite==3.46.0
    - libssh2==1.10.0
    - libstdcxx==14.2.0
    - libstdcxx-devel_linux-64==14.2.0
    - libstdcxx-ng==14.2.0
    - libtiff==4.4.0
    - libtool==2.4.7
    - libudev1==253
    - libvorbis==1.3.7
    - libwebp-base==1.4.0
    - libzlib==1.2.13
    - llvm-openmp==19.1.4
    - make==4.4.1
    - markdown==3.6
    - markupsafe==3.0.2
    - matplotlib-base==3.9.1
    - metis==5.1.0
    - mkl==2024.2.2
    - mkl-devel==2024.2.2
    - mkl-include==2024.2.2
    - mpfr==4.2.1
    - mpg123==1.31.3
    - multidict==6.1.0
    - munkres==1.1.4
    - mysql-common==8.0.32
    - mysql-connector-c==6.1.11
    - mysql-libs==8.0.32
    - ncbi-vdb==3.1.1
    - nccl==2.23.4.1
    - ncurses==6.5
    - nose==1.3.7
    - nspr==4.36
    - nss==3.100
    - oauthlib==3.2.2
    - openjpeg==2.5.0
    - opt_einsum==3.4.0
    - ossuuid==1.6.2
    - packaging==24.2
    - pandas==2.2.3
    - pango==1.50.12
    - parallel==20241122
    - pcre2==10.37
    - perl-app-cpanminus==1.7044
    - perl-business-isbn==3.004
    - perl-business-isbn-data==20140910.003
    - perl-carp==1.38
    - perl-constant==1.33
    - perl-data-dumper==2.173
    - perl-dbi==1.642
    - perl-encode==2.88
    - perl-encode-locale==1.05
    - perl-exporter==5.72
    - perl-exporter-tiny==1.002001
    - perl-extutils-makemaker==7.36
    - perl-file-path==2.16
    - perl-file-temp==0.2304
    - perl-list-moreutils-xs==0.428
    - perl-mime-base64==3.15
    - perl-parent==0.236
    - perl-uri==1.76
    - perl-xml-namespacesupport==1.12
    - perl-xml-sax==1.02
    - perl-xml-sax-base==1.09
    - perl-xsloader==0.24
    - pillow==9.2.0
    - pip==24.3.1
    - pixman==0.43.2
    - ply==3.11
    - propcache==0.2.0
    - protobuf==4.21.12
    - pthread-stubs==0.4
    - pulseaudio==14.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pycairo==1.25.0
    - pycparser==2.22
    - pydantic==1.10.17
    - pygobject==3.44.1
    - pyjwt==2.10.1
    - pyopenssl==23.2.0
    - pyparsing==3.2.0
    - pyqt==5.15.7
    - pyqt5-sip==12.11.0
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - python-flatbuffers==24.3.25
    - python-tzdata==2024.2
    - pytz==2024.1
    - pyu2f==0.1.5
    - qhull==2020.2
    - qt-main==5.15.6
    - r-askpass==1.1
    - r-bit==4.0.5
    - r-bit64==4.0.5
    - r-bitops==1.0_7
    - r-blob==1.2.4
    - r-cachem==1.0.8
    - r-cli==3.6.1
    - r-codetools==0.2_19
    - r-colorspace==2.1_0
    - r-cpp11==0.4.7
    - r-crayon==1.5.2
    - r-curl==4.3.3
    - r-dbi==1.1.3
    - r-domc==1.3.8
    - r-ellipsis==0.3.2
    - r-fansi==1.0.4
    - r-farver==2.1.1
    - r-fastmap==1.1.1
    - r-foreach==1.5.2
    - r-glue==1.6.2
    - r-gtable==0.3.3
    - r-httr==1.4.6
    - r-isoband==0.2.7
    - r-iterators==1.0.14
    - r-jsonlite==1.8.5
    - r-labeling==0.4.2
    - r-lattice==0.21_8
    - r-lifecycle==1.0.3
    - r-magrittr==2.0.3
    - r-mass==7.3_58.3
    - r-matrix==1.5_4.1
    - r-memoise==2.0.1
    - r-mgcv==1.8_42
    - r-mime==0.12
    - r-munsell==0.5.0
    - r-nlme==3.1_162
    - r-openssl==2.0.5
    - r-pillar==1.9.0
    - r-pkgconfig==2.0.3
    - r-plogr==0.2.0
    - r-plyr==1.8.8
    - r-png==0.1_8
    - r-r6==2.5.1
    - r-rcolorbrewer==1.1_3
    - r-rcpp==1.0.10
    - r-rcurl==1.98_1.12
    - r-rlang==1.1.1
    - r-rsqlite==2.3.1
    - r-scales==1.2.1
    - r-stringi==1.7.12
    - r-stringr==1.5.0
    - r-sys==3.4.2
    - r-tibble==3.2.1
    - r-utf8==1.2.3
    - r-vctrs==0.6.2
    - r-viridislite==0.4.1
    - r-withr==2.5.0
    - r-xml==3.99_0.11
    - re2==2022.06.01
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - rsa==4.9
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - sed==4.8
    - seqtk==1.4
    - sigcpp-2.0==2.10.8
    - sip==6.7.12
    - six==1.16.0
    - snappy==1.1.10
    - sparsehash==2.0.4
    - sqlite==3.46.0
    - sra-tools==3.1.1
    - suitesparse==5.10.1
    - tabixpp==1.1.0
    - tbb==2021.7.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-base==2.11.0
    - tensorflow-estimator==2.11.0
    - termcolor==2.5.0
    - texttable==1.7.0
    - threadpoolctl==3.5.0
    - tk==8.6.13
    - tktable==2.10
    - toml==0.10.2
    - tomli==2.2.1
    - tornado==6.4.2
    - tqdm==4.67.1
    - typing-extensions==4.12.2
    - typing_extensions==4.12.2
    - tzdata==2024b
    - unicodedata2==15.1.0
    - urllib3==2.2.3
    - vsearch==2.15.2
    - werkzeug==3.1.3
    - wheel==0.45.1
    - wrapt==1.17.0
    - xcb-util==0.4.0
    - xcb-util-image==0.4.0
    - xcb-util-keysyms==0.4.0
    - xcb-util-renderutil==0.3.9
    - xcb-util-wm==0.4.1
    - xorg-fixesproto==5.0
    - xorg-inputproto==2.3.2
    - xorg-kbproto==1.0.7
    - xorg-libice==1.0.10
    - xorg-libsm==1.2.3
    - xorg-libx11==1.8.4
    - xorg-libxau==1.0.11
    - xorg-libxdmcp==1.1.5
    - xorg-libxext==1.3.4
    - xorg-libxfixes==5.0.3
    - xorg-libxi==1.7.10
    - xorg-libxrender==0.9.10
    - xorg-libxt==1.3.0
    - xorg-libxtst==1.2.3
    - xorg-recordproto==1.14.2
    - xorg-renderproto==0.11.1
    - xorg-xextproto==7.3.0
    - xorg-xproto==7.0.31
    - yaml==0.2.5
    - yarl==1.18.0
    - zipp==3.21.0
    - zlib==1.2.13
    - zstandard==0.23.0

build:
  noarch: generic

test:
  command: "cd $PREFIX/SqueezeMeta/scripts; for script in *.pl; do perl -c $script; done; perl $PREFIX/SqueezeMeta/utils/install_utils/test_install.pl"

about:
  home:  https://github.com/jtamames/SqueezeMeta
  license: GPL-3
  license_file: ../../LICENSE
  summary: 'SqueezeMeta: a fully automated metagenomics pipeline, from reads to bins'
  description:
          "SqueezeMeta is a fully automatic pipeline for metagenomics/metatranscriptomics,
          covering all steps of the analysis. SqueezeMeta includes multi-metagenome
          support allowing the co-assembly of related metagenomes and the retrieval of
          individual genomes via binning procedures.
          \n
          \n
          To install this package with mamba run:
          \n
          \n
          `mamba create -n SqueezeMeta -c conda-forge -c bioconda -c fpusan squeezemeta-dev --no-channel-priority --override-channels`
          \n
          \n
          And activate it with:
          \n
          \n
          `conda activate SqueezeMeta`
          \n
          \n
          Detailed usage instructions can be found at <http://github.com/jtamames/SqueezeMeta>"
  dev_url: https://github.com/jtamames/SqueezeMeta
  doc_url: https://github.com/jtamames/SqueezeMeta
  doc_source_url: https://github.com/jtamames/SqueezeMeta/blob/master/README.md
  recipe-maintainers:
      - fpusan
